app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

account:
    path: /account

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
