services:
    app.email_support:
        class: AppBundle\Service\EmailSupport
        arguments:
            - '@mailer'
            - '@templating'
            - '%mailer_user%'
    app.token_service:
        class: AppBundle\Service\TokenService

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'


    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
