services:
    app.email_support:
        class: AppBundle\Service\EmailService
        arguments:
            - '@mailer'
            - '@templating'
            - '%mailer_user%'

    app.token_service:
        class: AppBundle\Service\TokenService
        arguments:
            - '@doctrine'

    app.user_provider:
        class: AppBundle\Security\User\UserProvider
        arguments:
            - '@doctrine'

    app.user_service:
        class: AppBundle\Service\UserService
        arguments:
            - '@security.password_encoder'

    app.latest_execution_service:
        class: AppBundle\Service\LatestExecutionService
        arguments:
            - '@kitpages_semaphore.manager'
            - '%latest_execution_file%'

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'


    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
